**Importacion de librerias**

In [1]:
import pandas as pd
import sqlalchemy
import psycopg2
from time import time

**Lectura del archivo .csv mediante la libreria panda definida como pd**

In [2]:
%%time
df = pd.read_csv("Supermarket sales.csv",delimiter=';')

Wall time: 31 ms

**Cambio de encabezados mediante un diccionario con pandas**

In [3]:
%%time
df = df.rename(columns={'Invoice ID': 'ID factura','Branch': 'Rama','City': 'Ciudad','Customer type': 'Tipo cliente',
                        'Gender': 'Genero','Product line': 'Linea de productos','Unit price': 'Precio unitario',
                        'Quantity': 'Cantidad','Tax 5%': 'Impuesto 5%','Date': 'Fecha','Time': 'Hora','Payment': 'Pago',
                        'cogs': 'Costo de vienes vendidos','gross margin percentage': 'Porcentaje de margen bruto',
                        'gross income': 'Ingresos brutos','Rating': 'Calificación'})
df

Wall time: 5 ms

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Member,Male,Electronic accessories,88.39,6,26.5170,556.8570,3/16/2019,15:10,Ewallet,530.34,4.761905,26.5170,7.6
2496,305-42-4107,C,Yangon,Normal,Female,Health and beauty,35.54,7,12.4390,261.2190,3/6/2019,18:23,Credit card,248.78,4.761905,12.4390,6.0
2497,716-40-0417,A,Yangon,Member,Male,Electronic accessories,62.65,4,12.5300,263.1300,1/20/2019,17:24,Cash,250.60,4.761905,12.5300,8.1
2498,706-85-4344,C,Mandalay,Normal,Female,Fashion accessories,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Cash,975.00,4.761905,48.7500,9.5
2499,372-16-3034,A,Mandalay,Normal,Female,Fashion accessories,32.25,4,6.4500,135.4500,2/16/2019,10:42,Ewallet,129.00,4.761905,6.4500,9.7

**Traducción de datos al español**

In [79]:
%%time
df["Pago"].replace({"Ewallet":"Monedero digital","Credit card":"Tarjeta de credito","Cash":"Efectivo" },inplace=True)
df["Genero"].replace({"Female":"Femenino","Male":"Mascuino"},inplace=True)
df["Linea de productos"].replace({"Health and beauty":"Salud y belleza","Electronic accessories":"Accesorios electrónicos",
                                 "Home and lifestyle":"Hogar y estilo de vida","Sports and travel":"Deportes y viajes",
                                 "Fashion accessories":"Accesorios de moda","Food and beverages":"Comida y bebidas"},inplace=True)
df["Tipo cliente"].replace({"Member":"Miembro"},inplace=True)
df

Wall time: 6.99 ms

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Miembro,Femenino,Salud y belleza,74.69,7,26.1415,548.9715,1/5/2019,13:08,Monedero digital,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Femenino,Accesorios electrónicos,15.28,5,3.8200,80.2200,3/8/2019,10:29,Efectivo,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Mascuino,Hogar y estilo de vida,46.33,7,16.2155,340.5255,3/3/2019,13:23,Tarjeta de credito,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Miembro,Mascuino,Salud y belleza,58.22,8,23.2880,489.0480,1/27/2019,20:33,Monedero digital,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Mascuino,Deportes y viajes,86.31,7,30.2085,634.3785,2/8/2019,10:37,Monedero digital,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Miembro,Mascuino,Accesorios electrónicos,88.39,6,26.5170,556.8570,3/16/2019,15:10,Monedero digital,530.34,4.761905,26.5170,7.6
2496,305-42-4107,C,Yangon,Normal,Femenino,Salud y belleza,35.54,7,12.4390,261.2190,3/6/2019,18:23,Tarjeta de credito,248.78,4.761905,12.4390,6.0
2497,716-40-0417,A,Yangon,Miembro,Mascuino,Accesorios electrónicos,62.65,4,12.5300,263.1300,1/20/2019,17:24,Efectivo,250.60,4.761905,12.5300,8.1
2498,706-85-4344,C,Mandalay,Normal,Femenino,Accesorios de moda,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Efectivo,975.00,4.761905,48.7500,9.5
2499,372-16-3034,A,Mandalay,Normal,Femenino,Accesorios de moda,32.25,4,6.4500,135.4500,2/16/2019,10:42,Monedero digital,129.00,4.761905,6.4500,9.7

# Limpieza de datos y cambio de datos #

**Calculo de impuesto**

In [4]:
%%time
df['Impuesto 5%']=df['Precio unitario']* df['Cantidad']*0.05
df

Wall time: 27.6 ms

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Member,Male,Electronic accessories,88.39,6,26.5170,556.8570,3/16/2019,15:10,Ewallet,530.34,4.761905,26.5170,7.6
2496,305-42-4107,C,Yangon,Normal,Female,Health and beauty,35.54,7,12.4390,261.2190,3/6/2019,18:23,Credit card,248.78,4.761905,12.4390,6.0
2497,716-40-0417,A,Yangon,Member,Male,Electronic accessories,62.65,4,12.5300,263.1300,1/20/2019,17:24,Cash,250.60,4.761905,12.5300,8.1
2498,706-85-4344,C,Mandalay,Normal,Female,Fashion accessories,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Cash,975.00,4.761905,48.7500,9.5
2499,372-16-3034,A,Mandalay,Normal,Female,Fashion accessories,32.25,4,6.4500,135.4500,2/16/2019,10:42,Ewallet,129.00,4.761905,6.4500,9.7

**Calculo del total**

In [5]:
%%time
df['Total']=df['Precio unitario']* df['Cantidad'] + df['Impuesto 5%']
df

Wall time: 5.4 ms

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Member,Male,Electronic accessories,88.39,6,26.5170,556.8570,3/16/2019,15:10,Ewallet,530.34,4.761905,26.5170,7.6
2496,305-42-4107,C,Yangon,Normal,Female,Health and beauty,35.54,7,12.4390,261.2190,3/6/2019,18:23,Credit card,248.78,4.761905,12.4390,6.0
2497,716-40-0417,A,Yangon,Member,Male,Electronic accessories,62.65,4,12.5300,263.1300,1/20/2019,17:24,Cash,250.60,4.761905,12.5300,8.1
2498,706-85-4344,C,Mandalay,Normal,Female,Fashion accessories,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Cash,975.00,4.761905,48.7500,9.5
2499,372-16-3034,A,Mandalay,Normal,Female,Fashion accessories,32.25,4,6.4500,135.4500,2/16/2019,10:42,Ewallet,129.00,4.761905,6.4500,9.7

**Calculo de costos de vienes vendidos**

In [6]:
%%time
df['Costo de vienes vendidos']=df['Precio unitario']* df['Cantidad']
df

Wall time: 1.01 ms

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Member,Male,Electronic accessories,88.39,6,26.5170,556.8570,3/16/2019,15:10,Ewallet,530.34,4.761905,26.5170,7.6
2496,305-42-4107,C,Yangon,Normal,Female,Health and beauty,35.54,7,12.4390,261.2190,3/6/2019,18:23,Credit card,248.78,4.761905,12.4390,6.0
2497,716-40-0417,A,Yangon,Member,Male,Electronic accessories,62.65,4,12.5300,263.1300,1/20/2019,17:24,Cash,250.60,4.761905,12.5300,8.1
2498,706-85-4344,C,Mandalay,Normal,Female,Fashion accessories,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Cash,975.00,4.761905,48.7500,9.5
2499,372-16-3034,A,Mandalay,Normal,Female,Fashion accessories,32.25,4,6.4500,135.4500,2/16/2019,10:42,Ewallet,129.00,4.761905,6.4500,9.7

**verificación porcentaje de margen bruto**

In [7]:
df['Porcentaje de margen bruto'].unique()

array([4.76190476, 4.761905  ])

**cambio de valor porcentaje de margen bruto**

In [8]:
df['Porcentaje de margen bruto'] = pd.unique(df['Porcentaje de margen bruto']) [0]
df

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Member,Male,Electronic accessories,88.39,6,26.5170,556.8570,3/16/2019,15:10,Ewallet,530.34,4.761905,26.5170,7.6
2496,305-42-4107,C,Yangon,Normal,Female,Health and beauty,35.54,7,12.4390,261.2190,3/6/2019,18:23,Credit card,248.78,4.761905,12.4390,6.0
2497,716-40-0417,A,Yangon,Member,Male,Electronic accessories,62.65,4,12.5300,263.1300,1/20/2019,17:24,Cash,250.60,4.761905,12.5300,8.1
2498,706-85-4344,C,Mandalay,Normal,Female,Fashion accessories,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Cash,975.00,4.761905,48.7500,9.5
2499,372-16-3034,A,Mandalay,Normal,Female,Fashion accessories,32.25,4,6.4500,135.4500,2/16/2019,10:42,Ewallet,129.00,4.761905,6.4500,9.7

**Cambio de ingresos brutos**

In [9]:
%%time
df['Ingresos brutos']=df['Costo de vienes vendidos']* (df['Porcentaje de margen bruto']/100)
df

Wall time: 1 ms

,ID factura,Rama,Ciudad,Tipo cliente,Genero,Linea de productos,Precio unitario,Cantidad,Impuesto 5%,Total,Fecha,Hora,Pago,Costo de vienes vendidos,Porcentaje de margen bruto,Ingresos brutos,Calificación
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,24.896667,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.638095,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,15.443333,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,22.179048,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,28.770000,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,063-71-2460,A,Naypyitaw,Member,Male,Electronic accessories,88.39,6,26.5170,556.8570,3/16/2019,15:10,Ewallet,530.34,4.761905,25.254286,7.6
2496,305-42-4107,C,Yangon,Normal,Female,Health and beauty,35.54,7,12.4390,261.2190,3/6/2019,18:23,Credit card,248.78,4.761905,11.846667,6.0
2497,716-40-0417,A,Yangon,Member,Male,Electronic accessories,62.65,4,12.5300,263.1300,1/20/2019,17:24,Cash,250.60,4.761905,11.933333,8.1
2498,706-85-4344,C,Mandalay,Normal,Female,Fashion accessories,97.50,10,48.7500,1023.7500,1/31/2019,19:39,Cash,975.00,4.761905,46.428571,9.5
2499,372-16-3034,A,Mandalay,Normal,Female,Fashion accessories,32.25,4,6.4500,135.4500,2/16/2019,10:42,Ewallet,129.00,4.761905,6.142857,9.7

**verificacion de calificaciones**

In [10]:
df['Calificación'].unique().tolist()

[9.1,
 9.6,
 7.4,
 8.4,
 5.3,
 4.1,
 5.8,
 8.0,
 7.2,
 5.9,
 4.5,
 6.8,
 7.1,
 8.2,
 5.7,
 4.6,
 6.9,
 8.6,
 4.4,
 4.8,
 5.1,
 9.9,
 6.0,
 8.5,
 6.7,
 7.7,
 7.5,
 7.0,
 4.7,
 7.6,
 7.9,
 6.3,
 5.6,
 9.5,
 8.1,
 6.5,
 6.1,
 6.6,
 5.4,
 9.3,
 10.0,
 6.4,
 4.3,
 4.0,
 8.7,
 9.4,
 5.5,
 8.3,
 7.3,
 4.9,
 4.2,
 9.2,
 7.8,
 5.2,
 9.0,
 8.8,
 6.2,
 9.8,
 9.7,
 5.0,
 8.9]

**Cargando datos en PostgreSQL**

In [11]:
%%time
engine = sqlalchemy.create_engine('postgresql://postgres:postgres@localhost:5432/Taller1')

df.to_sql('ventas',engine,if_exists='replace')

Wall time: 368 ms